config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resource :like, only:[:create]
    resource :retweet, only:[:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates_presence_of :body

  broadcasts_to -> (tweet){ :tweets }, inserts_by: :prepend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet

  def create
  	@tweet.increment! :likes_count
  	redirect_to @tweet
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :set_tweet

  def create
  	@tweet.increment! :retweets_count
  	redirect_to @tweet
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.order(created_at: :desc)
    @blank = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @blank = Tweet.new

    respond_to do |format|
      if @tweet.save
        format.turbo_stream
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: {tweet: @tweet}), status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= Time.now.strftime("%S") %>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= turbo_frame_tag tweet do %>
  <%= content_tag :div, data:{controller:"form"}, class:"tweet" do %>
    <%= form_with(model: tweet) do |form| %>
      <% if tweet.errors.any? %>
        <div style="color: red">
          <big><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</big>

          <ul>
            <% tweet.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.text_area :body, placeholder: "What is happening?", data:{form_target:"editor"} %>
      </div>

      <div class="row">
        <%= button_to("Like (#{tweet.likes_count})", tweet_like_path(tweet)) if tweet.persisted? %>
        <%= button_to("Retweet (#{tweet.retweets_count})", tweet_retweet_path(tweet)) if tweet.persisted? %>
        <%= form.submit(style:("display:none" if tweet.persisted?), data:{form_target:"submit"}) %>
        <%= link_to("Cancel", tweet, data:{form_target:"cancel"}) if tweet.persisted? %>
      </div>
    <% end %>    
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag tweet do %>
  <%= content_tag :div, data:{controller:"tweet"}, class:"tweet" do %>
    <%= content_tag :p, data:{action:"click->tweet#edit"} do %>
      <%= tweet.body %>
    <% end %>
    <div class="row">
      <%= button_to "Like (#{tweet.likes_count})", tweet_like_path(tweet) %>
      <%= button_to "Retweet (#{tweet.retweets_count})", tweet_retweet_path(tweet) %>
      <%= link_to "Edit", edit_tweet_path(tweet), data:{tweet_target:"edit"} %>
      <%= link_to "Delete", tweet, data: { "turbo-method": :delete } %>
    </div>
  <% end %>
<% end %>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend "tweets" do %>
  <%= render partial: "tweets/tweet", locals: { tweet: @tweet } %>
<% end %>
<%= turbo_stream.replace @blank do %>
  <%= render partial: "tweets/form", locals: { tweet: @blank } %>
<% end %>

app/views/tweets/destroy.turbo_stream.erb
<%= turbo_stream.remove(@tweet) %>

app/views/tweets/edit.html.erb
<p></p>

<%= render "form", tweet: @tweet %>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweeter</h1>

<%= turbo_stream_from "tweets" %>

<%#= turbo_frame_tag "new_tweet", src: new_tweet_path, target: "_top" %>
<%= render "form", tweet: @blank %>

<div id="tweets">
  <%= render @tweets %>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= turbo_frame_tag "new_tweet", target: "_top" do %>
  <%= render "form", tweet: @tweet %>
<% end %> 

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Back to tweets", tweets_path, "data-turbo-frame": "_top" %>
</div>